---
firewallA:
  hostname: 10.69.69.69
  groups:
    - 'Firewall'
  username: 'encryptedUsername'
  password: 'encryptedPassword'

switchA:
  groups:
  - Switch
  hostname: 192.168.69.69

routerA:
  groups:
  - Router
  hostname: 172.16.69.69